export type BookSize = 'small' | 'medium' | 'large' | 'tall' | 'wide'

export interface Book {
  id: string
  title: string
  author: string
  visitorName: string
  story: string
  dateAdded: string
  rotation: number // slight tilt in degrees for hand-drawn feel
  size: BookSize
  thickness: number // 1-5, affects the spine width and page edge depth
  audioUrl?: string // optional recording of the visitor telling their story
}

export const initialBooks: Book[] = [
  {
    id: '1',
    title: 'The Bell Jar',
    author: 'Sylvia Plath',
    visitorName: 'Mara, 24',
    story: 'I read this in the psych ward when I was nineteen. A nurse left it on my nightstand. I didn\'t ask for it. I remember thinking Plath understood something about me that I hadn\'t even said out loud yet. I kept it under my pillow for weeks. I\'m better now. I still have that copy.',
    audioUrl: '/audio/mara-bell-jar.mp3',
    dateAdded: '2025-03-15',
    rotation: -1.2,
    size: 'medium',
    thickness: 2,
  },
  {
    id: '2',
    title: 'Beloved',
    author: 'Toni Morrison',
    visitorName: 'James, 67',
    story: 'My mother never talked about her mother. There was a silence in our house that went back generations. When I read Beloved, I understood the silence. Not why it existed -- I already knew that. But that the silence was its own kind of language. I read it once a year now, on her birthday.',
    dateAdded: '2025-03-18',
    rotation: 0.8,
    size: 'large',
    thickness: 4,
  },
  {
    id: '3',
    title: 'The Little Prince',
    author: 'Antoine de Saint-Exupery',
    visitorName: 'Lia, 31',
    story: 'My father read this to me every night in Greek before he left. I was five. I didn\'t see him again until I was twenty-two. When we finally sat across from each other, neither of us knew what to say. So I pulled it from my bag and set it on the table between us. He cried. It was enough.',
    audioUrl: '/audio/lia-little-prince.mp3',
    dateAdded: '2025-04-02',
    rotation: -0.5,
    size: 'small',
    thickness: 1,
  },
  {
    id: '4',
    title: 'Man\'s Search for Meaning',
    author: 'Viktor E. Frankl',
    visitorName: 'Anonymous',
    story: 'I lost my son to an overdose in 2019. For a year I didn\'t read anything. I didn\'t do anything. A grief counselor gave me this book and I threw it across the room. But I picked it up eventually. It didn\'t fix me. Nothing fixes you. But Frankl convinced me that I could carry this and still mean something.',
    audioUrl: '/audio/anon-mans-search.mp3',
    dateAdded: '2025-04-10',
    rotation: 1.5,
    size: 'tall',
    thickness: 3,
  },
  {
    id: '5',
    title: 'Giovanni\'s Room',
    author: 'James Baldwin',
    visitorName: 'Eli, 28',
    story: 'I was raised in a town of 600 people in rural Texas. I knew I was gay at twelve. I found Baldwin in the public library when I was sixteen and read the whole thing sitting on the floor between shelves. That was the first time I thought: maybe there is a world for me somewhere.',
    audioUrl: '/audio/eli-giovannis-room.mp3',
    dateAdded: '2025-04-22',
    rotation: -0.9,
    size: 'medium',
    thickness: 2,
  },
  {
    id: '6',
    title: 'When Breath Becomes Air',
    author: 'Paul Kalanithi',
    visitorName: 'Dr. Chen, 45',
    story: 'I am an oncologist. I give people bad news for a living. I know the clinical language for every kind of dying. This book reminded me that on the other side of every diagnosis I deliver, there is someone trying to figure out how to keep living. I keep it in my desk drawer at the hospital.',
    dateAdded: '2025-05-01',
    rotation: 0.4,
    size: 'small',
    thickness: 2,
  },
  {
    id: '7',
    title: 'The God of Small Things',
    author: 'Arundhati Roy',
    visitorName: 'Priya, 37',
    story: 'I was born in Kerala, like the twins in the book. I left when I was ten and never went back. Roy writes about that place like she\'s pulling it out of my chest. The love laws. The things that are allowed and not allowed. I have never felt so seen and so destroyed by the same book.',
    dateAdded: '2025-05-14',
    rotation: -1.8,
    size: 'wide',
    thickness: 3,
  },
  {
    id: '8',
    title: 'A Little Life',
    author: 'Hanya Yanagihara',
    visitorName: 'S., 26',
    story: 'I know everyone says this book is too much. I know. But I was in an abusive relationship for four years and nobody talked about what it does to you after. Not the bruises. The after. This book understood the after. I have never underlined so many sentences in my life.',
    dateAdded: '2025-05-28',
    rotation: 0.7,
    size: 'large',
    thickness: 5,
  },
  {
    id: '9',
    title: 'The Giving Tree',
    author: 'Shel Silverstein',
    visitorName: 'Tom, 72',
    story: 'My wife of forty-four years just passed. She read this to all three of our kids every night. I couldn\'t read it for months after she died. Then one night my granddaughter climbed into my lap with it. I read it to her and I could hear my wife\'s voice in my own. I don\'t know what that means but it meant everything.',
    audioUrl: '/audio/tom-giving-tree.mp3',
    dateAdded: '2025-06-05',
    rotation: -0.3,
    size: 'small',
    thickness: 1,
  },
  {
    id: '10',
    title: 'The Stranger',
    author: 'Albert Camus',
    visitorName: 'K., 19',
    story: 'I read this the week I dropped out of college. Everyone was panicking but me. I felt nothing. Then Meursault felt nothing. And I realized that feeling nothing was its own kind of feeling, and that scared me enough to call my mom. I\'m back in school now. Different school though.',
    dateAdded: '2025-06-18',
    rotation: 1.1,
    size: 'medium',
    thickness: 1,
  },
  {
    id: '11',
    title: 'Crying in H Mart',
    author: 'Michelle Zauner',
    visitorName: 'Joon, 33',
    story: 'My mom is Korean. I\'m adopted. I grew up in Minnesota with white parents who loved me but couldn\'t teach me kimchi jjigae. I read this book in one sitting and sobbed for two hours. Not because I lost a mother, but because I never had the one I was supposed to.',
    dateAdded: '2025-07-02',
    rotation: -1.4,
    size: 'medium',
    thickness: 3,
  },
  {
    id: '12',
    title: 'The Prophet',
    author: 'Kahlil Gibran',
    visitorName: 'Rania, 58',
    story: 'We read from this at my daughter\'s wedding. We read from it at my husband\'s funeral. The same book held both days. Gibran wrote that joy and sorrow are inseparable. I didn\'t believe it when I was young. Now I know it\'s the truest thing anyone ever wrote.',
    audioUrl: '/audio/rania-prophet.mp3',
    dateAdded: '2025-07-20',
    rotation: 0.6,
    size: 'tall',
    thickness: 2,
  },
  {
    id: '13',
    title: 'Norwegian Wood',
    author: 'Haruki Murakami',
    visitorName: 'Daniel, 29',
    story: 'My best friend killed himself our junior year of college. I stopped sleeping. I stopped eating. Someone put Murakami in my hands and said "he writes about loss the way it actually feels." They were right. It doesn\'t resolve. It just goes on. And somehow that was what I needed to hear.',
    dateAdded: '2025-08-03',
    rotation: -0.6,
    size: 'large',
    thickness: 3,
  },
  {
    id: '14',
    title: 'Where the Wild Things Are',
    author: 'Maurice Sendak',
    visitorName: 'Grace, 40',
    story: 'I read this to my daughter the night before her first day of kindergarten. She was terrified. I told her she was Max and the world was full of wild things but that she would always have a home to come back to where her supper would be waiting. She\'s in high school now. She still references it when she\'s scared.',
    dateAdded: '2025-08-15',
    rotation: 1.3,
    size: 'wide',
    thickness: 2,
  },
  {
    id: '15',
    title: 'Night',
    author: 'Elie Wiesel',
    visitorName: 'Anonymous',
    story: 'I am the granddaughter of a survivor. My grandfather never spoke about what happened. He died when I was fourteen. Two years later my mother gave me this book and said "now you\'ll understand why he couldn\'t talk about it." I have never been the same person I was before I read it.',
    audioUrl: '/audio/anon-night.mp3',
    dateAdded: '2025-09-01',
    rotation: -1.0,
    size: 'small',
    thickness: 2,
  },
]
